### ISSUE TITLE
Navigation events

### ISSUE THREAD

**Issue by maximedupre** [EmilTholin/svelte-routing#121] opened 2020-03-20 21:34 UTC
When navigating to one of my routes, there is a noticeable delay before the component is displayed. Does `svelte-routing` provide any event that would allow me to show and hide a progress bar (when the navigation starts and ends)?

On the same note, I think there should be some option that would allow for the component to be loaded only once, then toggled when the route changes, in order to avoid loading the whole component trees.

Cheers!

**EDIT # 1**

I guess the delay has to do with the fact that components are loaded synchronously,  thus blocking the page if there is some processing. Am I right to think that the only solution is to lazy-load component with something like `svelte-loadable`?

**EDIT # 2**

[Using `svelte-loadable` does not seem to help](https://github.com/kaisermann/svelte-loadable/issues/30). It's pretty weird that my component loads quickly when loading the page initially. Only once it is loaded via `svelte-routing`, because a route has been activated ,is there a ~1 second delay before my component is shown.

**Comment by EmilTholin** [comment] 2020-05-19 10:49
Hi @maximedupre!

Do you have a minimal reproducible example that we could ideally clone and try out? There should not be any delay when navigating since the component code is already loaded by your browser and ready to be rendered straight away.

**Comment by EmilTholin** [comment] 2020-12-31 06:44
Closing this as I can't reproduce it. Feel free to re-open or comment with a minimal reproducible example if the problem persists.

**Closed by EmilTholin** 2020-12-31 06:44 UTC

**Comment by mpro7** [comment] 2021-05-28 14:01
@EmilTholin is there any event fired on the route change?
