### ISSUE TITLE
<Route path ="some urls " component={component}  > this cannot access directly url

### ISSUE THREAD

**Issue by hananloser** [EmilTholin/svelte-routing#94] opened 2019-12-21 11:00 UTC
when i refresh browser page not found i installed on laravel `<script>
  import Login from "./auth/login.svelte";
  import Cars from "./Cars/Cars.svelte";
  import { Router, Route, Link, replace } from "svelte-routing";
</script>

<Router>
  <Route path="/admin" component={Login} />
  <Route path="/admin/cars/*">
    <Cars />
  </Route>
</Router>
`
when i access `"/admin/cars/*` not found but i click Link to navigate thats route nice work

**Comment by Heydan83** [comment] 2019-12-21 23:02
I have the same issue, when calling the routes from code (meaning clicking an anchor) they work, but if you type the URL route in the navigator it cannot be found, it shows the 404 error, page not found.

**Comment by EmilTholin** [comment] 2019-12-21 23:07
This is not `svelte-routing` specific. You must make sure your server serves the `index.html` file for all your routes.

Closing as duplicate of https://github.com/EmilTholin/svelte-routing/issues/32.

**Closed by EmilTholin** 2019-12-21 23:07 UTC

**Comment by the-einstein** [comment] 2020-05-18 06:20
What should I do for a single page application? I am not using any server and I need to refresh my page, but every time I am getting error. I am using webpack for now, While using rollup I could use `-s` to run it without errors in spa. What should I do for SPA in webpack?
