### ISSUE TITLE
When user navigates to route in address bar, not found

### ISSUE THREAD

**Issue by willnix86** [EmilTholin/svelte-routing#101] opened 2020-01-21 21:02 UTC
I want a user to be able to get to one of my routes when linked to it from outside the application, but the page is never found.

For example: a user clicks on a link to https://www.mywebsite/sub-page on another website but instead of reaching that path, they get a 'not found' error. They would have to specifically go to www.mywebsite.com and then access the sub-page from there.

Any thoughts on a fix for this?

**Comment by EmilTholin** [comment] 2020-01-21 23:48
Hi @willnix86!

You have to make sure your server serves the `index.html` file for all your routes and not just for the `/` path. How to do this is very dependent on what server you are using.

I'm closing this as a duplicate of https://github.com/EmilTholin/svelte-routing/issues/32.

**Closed by EmilTholin** 2020-01-21 23:48 UTC

**Comment by willnix86** [comment] 2020-01-21 23:57
Thank you, Emil! Super helpful 😊
