### ISSUE TITLE
Backwards routing on mobile sometimes not working

### ISSUE THREAD

**Issue by elieven** [EmilTholin/svelte-routing#87] opened 2019-10-31 22:29 UTC
About 1 out of 3 or 4 times i open a simple app with svelte-routing on my mobile device (chrome browser) the backwards routing in history does not work. Even using all default simple templates. It always works for forward routing but then just breaks at backwards. Happens very inconsistently so i doubt i could say what specifically it is.

**Comment by EmilTholin** [comment] 2019-11-14 10:32
Hi @elieven!

That's frustrating. There is not enough information for me to take a look at it, sadly. If you do find a minimal reproducible example that we can ideally clone and try, it would be great if you shared that.

**Comment by EmilTholin** [comment] 2019-11-29 10:52
Closing this. We can open it again if we find a minimal reproducible example. Can't reproduce it as of now.

**Closed by EmilTholin** 2019-11-29 10:52 UTC
